### ISSUE TITLE
Front end design plan

### ISSUE THREAD

**Issue by evanrcooper** [ECE-366-Final-Project/front_end#1]

**Comment by LaniW** [comment]
Just finished all (that I can think of) issues that we will meet while developing the frontend. 
Could @evanrcooper @Vaibhav-Hariani or @secureshellprotocol look through them to check for missing issues or to make sure we are all on the same page?

**Comment by LaniW** [comment]
Thank you all for the consensus and the meeting. We will continue to meet weekly to discuss any changes as we progress.
