### ISSUE TITLE
Rudimentary Transaction History UI

### ISSUE THREAD

**Issue by LaniW** [ECE-366-Final-Project/front_end#10]
**Get the following up on the _transaction history page_:**

- nav bar with: Home icon, account, slots and blackjack options
- Card: balance amount, game played (if made) and the amount added/deducted 
- Feed: a scrollable list of cards

**Comment by LaniW** [comment]
The following issues will be addressed once further connection between the backend and front end is established:

- The nav bar games section still has empty links since none of them have been linked at the time.
- The refresh button has no connection to the backend and just generates a default transaction card on press.

**Comment by LaniW** [comment]
![image](https://github.com/ECE-366-Final-Project/front_end/assets/60847314/7ac6dfeb-0e86-43c0-a5ee-a750835aee95)
![image](https://github.com/ECE-366-Final-Project/front_end/assets/60847314/c6011f29-fdcf-443f-831d-37edaeb3e448)

**Comment by Vaibhav-Hariani** [comment]
Completed.
