### ISSUE TITLE
Rudimentary Account Login Page UI

### ISSUE THREAD

**Issue by LaniW** [ECE-366-Final-Project/front_end#11]
**Get the following up on the _Account Login Page_:**

- Username text entry
- Password text entry
- Login verification button => either denies login or allows access to the home page

**Comment by LaniW** [comment]
The following issues are known about this draft and will be fixed once further connection is made between the backend and the front end:

- Text input in any text field has no impact on the login or account creation. 
- Login button -> Home page (directly)

**Comment by LaniW** [comment]
![image](https://github.com/ECE-366-Final-Project/front_end/assets/60847314/7572e419-5afe-4456-bb48-d6cd0f6cae6c)
![image](https://github.com/ECE-366-Final-Project/front_end/assets/60847314/bc47c615-99c5-4d53-970e-52eb41329e0a)

**Comment by Vaibhav-Hariani** [comment]
Integrated Login with backend.
