### ISSUE TITLE
Rudimentary Slots Page UI

### ISSUE THREAD

**Issue by LaniW** [ECE-366-Final-Project/front_end#12]
**Get the following up on the _Slots Page_:**

- nav bar with: Home icon, account, slots and blackjack options
- slots machine graphic that acts like a real slots machine based on the following
- animated button (card or cash insert) that 1. determines if you are betting an allowed amount 2. deducts from the balance if valid 3. allows for the activation of the handle button
- animated button (crank handle) that determines the slots combination
- spinning slot cells entry that displays the slots combination
- popup card that shows up after you play it displays 1.the amount gained/loss 2. your current balance 3. a button to continue => closes the popup and resets the game 4. a button to cash out => returns to the home page

**Comment by Vaibhav-Hariani** [comment]
Completed Rudimentary Slots UI.
