### ISSUE TITLE
Decorated Blackjack Page UI

### ISSUE THREAD

**Issue by LaniW** [ECE-366-Final-Project/front_end#17]
**Get the following up on the _blackjack page_:**

- Green, felt-like background with 
- Contrasting tray color (deep blue, orange, purple, something not in use for chips etc.)
- Chip button colors 
- An accompanying overall font: Gotham, and Poppins
- An accompanying font for cards: Fonts that use serifs (typical for card decks)
- The game content should be relatively centered (deals, bet decisions, etc.)

_Some ideas for additions include:_
- Anchor the tray to show up as a bottom nav
- Have text buttons show up on the sides (directly left or right) of the game content

**Comment by Vaibhav-Hariani** [comment]
Vaibhav Completed!
