### ISSUE TITLE
Decorated Slots UI

### ISSUE THREAD

**Issue by LaniW** [ECE-366-Final-Project/front_end#18]
**Get the following up on the _slots page_:**

- Black background with either
- Las Vegas: black, red, gold, white accents
- Fluorescent/Neon: red, white, blue, yellow, accents with a glow
- An accompanying font: Gotham, Montserrat, or Poppins

_Some ideas for additions include:_
- Something extravagant when a Jackpot is met (window flashes through a series of color?)
- Red for deductions, green for wins

**Comment by Vaibhav-Hariani** [comment]
UI In presentation format is completed: Will change style if we decide to do so.
