### ISSUE TITLE
Rudimentary Account Creation Page UI

### ISSUE THREAD

**Issue by LaniW** [ECE-366-Final-Project/front_end#31]
**Get the following up on the _Account Creation Page_:**

- Username text entry
- Password text entry
- Password text re entry
- Login verification button => either denies creation or goes back to the account-login page

**Comment by LaniW** [comment]
The following issues are known about this draft and will be fixed once further connection is made between the backend and the front end:

- Text input in any text field has no impact on each other or account creation

**Comment by LaniW** [comment]
![image](https://github.com/ECE-366-Final-Project/front_end/assets/60847314/0ebb19f7-b615-4c10-a8df-fa9fcdd65537)
![image](https://github.com/ECE-366-Final-Project/front_end/assets/60847314/3f443ebe-ba2f-48bf-bd1b-48e87cb6a196)

**Comment by Vaibhav-Hariani** [comment]
Added Relevant Functionality.
