### ISSUE TITLE
Write a README

### ISSUE THREAD

**Issue by LaniW** [ECE-366-Final-Project/front_end#7]
**Add steps for the following (based on the README of the backend):**

- Authors
- Cloning the repo
- List of Flutter dependencies
- Build and run
- Images regarding the current state of the Main branch
- Change the Repo description to reflect Dart/Flutter

**Comment by secureshellprotocol** [comment]
Hi, started now, not sure what to jot down for some flutter dependencies or building & running. For the flutter, how do we build a flutter app? is it done via vscode or through command-line. Thanks!

**Comment by LaniW** [comment]
Hi! I have mainly been doing it in VSCode with powershell and the command `flutter run` which also builds and compiles the app aside from running it. I am not exactly sure how to do it on Linux but it looks like the [same command](https://docs.flutter.dev/get-started/install/linux) is used! Dependencies are packages that will probably come up as we continue to develop it. Any used will show up in the pubspec.yaml file. Within the main directory of the front_end repository. 

![image](https://github.com/ECE-366-Final-Project/front_end/assets/60847314/b52094ea-1f1d-4388-9d14-c6759b002374)

**Comment by secureshellprotocol** [comment]
Got it! it seems like `flutter run` should just handle the legwork on dependency resolution, then. We can just stick with telling people about the run command.
