### ISSUE TITLE
Rudimentary Deposit/Withdrawal Page UI

### ISSUE THREAD

**Issue by LaniW** [ECE-366-Final-Project/front_end#9]
**Get the following up on the _deposit/withdrawal page_:**

- nav bar with: Home icon, account, slots and blackjack options
- updatable balance
- button for deposit => text entry to enter in an amount to deposit
- button for withdrawal => text entry to enter in an amount to deposit

**Comment by LaniW** [comment]
The following issues are known about this draft and will be fixed once further connection is made between the backend and the front end:

- The nav bar issues (games linked to landing, user account links to landing, and balance links to landing) are also unresolved.
- The keypad has a couple of loose screws. These issues include
   ~ The negative sign appears within the dollar sign
   ~ The value is always some integer value
   ~ There might be more errors with the delete button as it is a bit finicky

I am not sure if any of those can be resolved by the backend but if not after review, I can go back in to fix them.

**Comment by LaniW** [comment]
![image](https://github.com/ECE-366-Final-Project/front_end/assets/60847314/d2afeff3-40d0-4760-84a9-d280ab7b7f06)
![image](https://github.com/ECE-366-Final-Project/front_end/assets/60847314/4dc9a4b9-a767-41ae-b339-2cc26d0417ce)
![image](https://github.com/ECE-366-Final-Project/front_end/assets/60847314/115a1657-9389-44ce-ad09-625a43927a8c)
![image](https://github.com/ECE-366-Final-Project/front_end/assets/60847314/bfcd79ea-c96e-4c2a-9b8a-a0ae14dba965)

**Comment by Vaibhav-Hariani** [comment]
Added Functioning Depsoit & Withdrawl functionality.
